/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chapter4_NativeDemo_NativeDemo */

#ifndef _Included_chapter4_NativeDemo_NativeDemo
#define _Included_chapter4_NativeDemo_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chapter4_NativeDemo_NativeDemo
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_chapter4_NativeDemo_NativeDemo_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
